POST http://localhost:8095/loanservice
Content-Type: application/json

{
	"idLoan" : 0,
	"book" : {
		"idbook": 2,
		"title": "New Art",
		"author": "Charlie Shuh",
		"description": "Lorem Ipsum",
		"pagecount": 250
	}
}
###
POST http://localhost:8095/loanservice
Content-Type: application/json

{
	"idLoan" : 0,
	"book" : {
      "idbook": 1,
      "title": "new book",
      "author": "T. Est",
      "description": "",
      "pagecount": 438
    }
}
###
POST http://localhost:8095/loanservice
Content-Type: application/json

{
	"idLoan" : 0,
	"book" : {
      "idbook" : 0,
      "title" : "SWE 2",
      "author" : "J. R.",
      "description" : "Lorem Ipsum, Lorem Ipsum",
      "pagecount" : 499
    }
}
###
GET http://localhost:8095/loanservice/loans
###
http://localhost:8095/loanservice/loans/1
###
http://localhost:8095/loanservice/loans/23
###
DELETE http://localhost:8095/loanservice/loans/1